version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST}
        - DB_DATABASE=${DB_DATABASE}
        - APP_NAME=${APP_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - db
    command: ["bash", "-c", "php artisan migrate:fresh --seed && php-fpm"]

  web-server:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
volumes:
  mysql_data:
