# This is a basic workflow that is manually triggered
name: Basic Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - staging
jobs:
  my_job:
    name: deploay staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Modify docker-compose.yaml to use github secrets
        run: |
          sed -i 's|${DB_HOST}|${{ secrets.DB_HOST}}|g' docker-compose.yaml
          sed -i 's|${DB_DATABASE}|${{ secrets.DB_DATABASE}}|g' docker-compose.yaml
          sed -i 's|${APP_NAME}|${{ secrets.APP_NAME}}|g' docker-compose.yaml
          sed -i 's|${DB_USERNAME}|${{ secrets.DB_USERNAME}}|g' docker-compose.yaml
          sed -i 's|${DB_PASSWORD}|${{ secrets.DB_PASSWORD}}|g' docker-compose.yaml
          sed -i 's|${MYSQL_ROOT_PASSWORD}|${{ secrets.DB_PASSWORD}}|g' docker-compose.yaml
          sed -i 's|${MYSQL_DATABASE}|${{ secrets.DB_DATABASE}}|g' docker-compose.yaml
          cat docker-compose.yaml

      - name: Docker Buildx Bake and push
        uses: docker/bake-action@v4.5.0
        with:
          file: docker-compose.yaml
          push: true
          set: "tags=${{ secrets.DOCKER_USERNAME }}/coffeshopup:latest"
